In [32]:
import polars as pl

corpus = pl.scan_parquet("..\\data\\raw\\dataset_depresion.parquet")

In [34]:
corpus = (
    corpus.with_columns(
        LENG_TEXT = pl.col("text").str.len_chars()
    )
)

In [36]:
# Calcular estadísticas básicas
stats = corpus.select([
    pl.col("LENG_TEXT").mean().alias("promedio"),
    pl.col("LENG_TEXT").max().alias("máximo"),
    pl.col("LENG_TEXT").min().alias("mínimo"),
    pl.col("LENG_TEXT").median().alias("mediana"),
    pl.col("LENG_TEXT").std().alias("desviación_std")
]).collect()

display(stats)

shape: (1, 5)
┌─────────────┬────────┬────────┬─────────┬────────────────┐
│ promedio    ┆ máximo ┆ mínimo ┆ mediana ┆ desviación_std │
│ ---         ┆ ---    ┆ ---    ┆ ---     ┆ ---            │
│ f64         ┆ u32    ┆ u32    ┆ f64     ┆ f64            │
╞═════════════╪════════╪════════╪═════════╪════════════════╡
│ 1220.984155 ┆ 10249  ┆ 79     ┆ 898.0   ┆ 1135.214002    │
└─────────────┴────────┴────────┴─────────┴────────────────┘

In [39]:
# Conteo de frecuencia de longitudes
distribucion = (
    corpus.group_by("LENG_TEXT")
    .len()
    .sort("LENG_TEXT")
    .collect()
)

display(distribucion.head(10))

shape: (10, 2)
┌───────────┬─────┐
│ LENG_TEXT ┆ len │
│ ---       ┆ --- │
│ u32       ┆ u32 │
╞═══════════╪═════╡
│ 79        ┆ 2   │
│ 86        ┆ 1   │
│ 88        ┆ 1   │
│ 100       ┆ 1   │
│ 101       ┆ 2   │
│ 102       ┆ 2   │
│ 103       ┆ 1   │
│ 104       ┆ 1   │
│ 105       ┆ 1   │
│ 106       ┆ 1   │
└───────────┴─────┘